/**
 * GitHub automation — commit, push, and open PR after tests pass.
 */
const { Octokit } = require('@octokit/rest');
const simpleGit = require('simple-git');
const config = require('../config');
const { createLogger } = require('../logger');

const log = createLogger('github');

function assertSafeAutofixBranch(branchName) {
  const lower = branchName.toLowerCase();
  const blocked = [config.GITHUB_BASE_BRANCH, 'main', 'master', ...config.protectedBranches];
  if (blocked.some((b) => b.toLowerCase() === lower)) {
    throw new Error(`Cannot modify protected branch: ${branchName}`);
  }
  if (!branchName.startsWith('autofix/')) {
    throw new Error(`Autofix must use autofix/* branches, got: ${branchName}`);
  }
}

function getOctokit() {
  if (!config.GITHUB_TOKEN) {
    throw new Error('GITHUB_TOKEN is required for GitHub automation');
  }
  return new Octokit({ auth: config.GITHUB_TOKEN });
}

async function commitAndPush({ branchName, message, files }) {
  assertSafeAutofixBranch(branchName);
  const git = simpleGit(config.projectRoot);
  const branches = await git.branchLocal();
  if (branches.all.includes(branchName)) {
    await git.checkout(branchName);
  } else if (branches.all.includes(config.GITHUB_BASE_BRANCH)) {
    await git.checkoutBranch(branchName, config.GITHUB_BASE_BRANCH);
  } else {
    await git.checkout(['-b', branchName]);
  }

  const relativePaths = files.map((f) => f.replace(/\\/g, '/'));
  await git.add(relativePaths);
  await git.commit(message);
  await git.push('origin', branchName, ['--set-upstream']);

  log.info('Pushed autofix branch', { branchName, files: relativePaths.length });
  return { branchName, commitMessage: message };
}

async function createPullRequest({ branchName, title, body }) {
  const octokit = getOctokit();
  const { data } = await octokit.pulls.create({
    owner: config.GITHUB_OWNER,
    repo: config.GITHUB_REPO,
    title,
    head: branchName,
    base: config.GITHUB_BASE_BRANCH,
    body
  });

  log.info('Pull request created', { url: data.html_url, number: data.number });
  return data;
}

async function publishFix({ summary, changedFiles }) {
  if (!config.GITHUB_OWNER || !config.GITHUB_REPO) {
    throw new Error('GITHUB_OWNER and GITHUB_REPO must be set');
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const branchName = `autofix/ai-${timestamp}`;
  assertSafeAutofixBranch(branchName);
  const message = `fix(autofix): ${summary}`;
  const pushResult = await commitAndPush({
    branchName,
    message,
    files: changedFiles
  });

  const pr = await createPullRequest({
    branchName: pushResult.branchName,
    title: `🤖 Autofix: ${summary}`,
    body: [
      '## Summary',
      summary,
      '',
      '## Changed files',
      ...changedFiles.map((f) => `- \`${f}\``),
      '',
      '---',
      '*Generated by ai-autofix-system*'
    ].join('\n')
  });

  return { branchName, prUrl: pr.html_url, prNumber: pr.number };
}

module.exports = { commitAndPush, createPullRequest, publishFix };
